// this file for default data thats replace the broken api server  
export const Courses = [
  {
    _id: "1",
    title: "React for Beginners",
    description: "Learn the basics of React in this beginner-friendly course.",
    instructor: {
      _id: "instructor1",
      firstName: "John",
      lastName: "Doe",
      fullName: "John Doe",
      profilePic: "/home/person1.png",
    },
    sections: [],
    price: 49,
    category: "Development",
    level: "Beginner",
    language: ["English"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card1.png",
    averageRating: 4.6,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-10-20"),
    duration: 12,
  },
  {
    _id: "2",
    title: "Advanced CSS and Sass",
    description: "Master advanced styling techniques using CSS and Sass.",
    instructor: {
      _id: "instructor2",
      firstName: "Jane",
      lastName: "Smith",
      fullName: "Jane Smith",
      profilePic: "/home/person2.png",
    },
    sections: [],
    price: 99,
    category: "Design",
    level: "Intermediate",
    language: ["English"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card2.png",
    averageRating: 4.8,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-11-01"),
    duration: 25,
  },
  {
    _id: "3",
    title: "Intro to Digital Marketing",
    description: "An introduction to modern digital marketing fundamentals.",
    instructor: {
      _id: "instructor3",
      firstName: "Sam",
      lastName: "Wilson",
      fullName: "Sam Wilson",
      profilePic: "/home/person3.png",
    },
    sections: [],
    price: 0,
    category: "Marketing",
    level: "Beginner",
    language: ["French"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card3.png",
    averageRating: 4.2,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-09-15"),
    duration: 5,
  },
  {
    _id: "4",
    title: "Complete Python Bootcamp",
    description: "Become a Python expert with this all-in-one bootcamp.",
    instructor: {
      _id: "instructor4",
      firstName: "Emily",
      lastName: "White",
      fullName: "Emily White",
      profilePic: "/home/person4.png",
    },
    sections: [],
    price: 199,
    category: "IT & Software",
    level: "All Levels",
    language: ["English"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card4.png",
    averageRating: 4.7,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-11-05"),
    duration: 40,
  },
  {
    _id: "5",
    title: "Photography Masterclass",
    description: "A complete guide to professional photography techniques.",
    instructor: {
      _id: "instructor5",
      firstName: "Chris",
      lastName: "Green",
      fullName: "Chris Green",
      profilePic: "/home/person1.png",
    },
    sections: [],
    price: 79,
    category: "Photography",
    level: "All Levels",
    language: ["Arabic"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card1.png",
    averageRating: 4.9,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-08-10"),
    duration: 15,
  },
  {
    _id: "6",
    title: "Business Fundamentals",
    description: "Essential knowledge for starting and managing a business.",
    instructor: {
      _id: "instructor6",
      firstName: "Patricia",
      lastName: "Black",
      fullName: "Patricia Black",
      profilePic: "/home/person2.png",
    },
    sections: [],
    price: 0,
    category: "Business",
    level: "Beginner",
    language: ["English"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card2.png",
    averageRating: 4.0,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-11-10"),
    duration: 8,
  },
  {
    _id: "7",
    title: "UI/UX Design Essentials",
    description: "Foundational course for UI/UX design principles and tools.",
    instructor: {
      _id: "instructor7",
      firstName: "Michael",
      lastName: "Brown",
      fullName: "Michael Brown",
      profilePic: "/home/person3.png",
    },
    sections: [],
    price: 129,
    category: "Design",
    level: "Intermediate",
    language: ["English"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card3.png",
    averageRating: 4.5,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-07-22"),
    duration: 22,
  },
  {
    _id: "8",
    title: "Expert JavaScript",
    description: "Advanced JavaScript concepts and real-world applications.",
    instructor: {
      _id: "instructor8",
      firstName: "Sarah",
      lastName: "Jones",
      fullName: "Sarah Jones",
      profilePic: "/home/person4.png",
    },
    sections: [],
    price: 299,
    category: "Development",
    level: "Expert",
    language: ["English"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card4.png",
    averageRating: 3.8,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-06-30"),
    duration: 50,
  },
  {
    _id: "9",
    title: "SQL for Data Science",
    description: "Learn SQL basics and data querying for data science.",
    instructor: {
      _id: "instructor9",
      firstName: "Mohammed",
      lastName: "Ali",
      fullName: "Mohammed Ali",
      profilePic: "/home/person1.png",
    },
    sections: [],
    price: 89,
    category: "IT & Software",
    level: "Intermediate",
    language: ["Arabic"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card1.png",
    averageRating: 4.4,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-10-25"),
    duration: 10,
  },
  {
    _id: "10",
    title: "Short Course on Vue.js",
    description: "Quickly get started with Vue.js and build simple apps.",
    instructor: {
      _id: "instructor10",
      firstName: "Pierre",
      lastName: "Dubois",
      fullName: "Pierre Dubois",
      profilePic: "/home/person2.png",
    },
    sections: [],
    price: 29,
    category: "Development",
    level: "Beginner",
    language: ["French"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card2.png",
    averageRating: 4.1,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-11-11"),
    duration: 0.5,
  },
   {
    _id: "11",
    title: "SQL for Data Science",
    description: "Learn SQL basics and data querying for data science.",
    instructor: {
      _id: "instructor9",
      firstName: "Mohammed",
      lastName: "Ali",
      fullName: "Mohammed Ali",
      profilePic: "/home/person1.png",
    },
    sections: [],
    price: 89,
    category: "IT & Software",
    level: "Intermediate",
    language: ["Arabic"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card1.png",
    averageRating: 4.4,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-10-25"),
    duration: 10,
  },
  {
    _id: "12",
    title: "Complete Python Bootcamp",
    description: "Become a Python expert with this all-in-one bootcamp.",
    instructor: {
      _id: "instructor4",
      firstName: "Emily",
      lastName: "White",
      fullName: "Emily White",
      profilePic: "/home/person4.png",
    },
    sections: [],
    price: 199,
    category: "IT & Software",
    level: "All Levels",
    language: ["English"],
    requirements: [],
    whatYouWillLearn: [],
    tags: [],
    thumbnail: "/home/card4.png",
    averageRating: 4.7,
    totalReviews: 0,
    totalStudents: 0,
    isPublished: true,
    approvalStatus: "approved",
    createdAt: new Date("2023-11-05"),
    duration: 40,
  },
];

export const Instructors = Array.from(
  new Map(
    Courses.map((course) => [course.instructor._id, course.instructor])
  ).values()
);//hahahahaha hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahhaha